#!/usr/bin/env node
// Reads .env (if present) plus process.env, and writes config.js as a plain
// global (window.__CONFIG__) for index.html to load before app.js.
// Deliberately dependency-free: this repo ships zero npm packages.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const OUT_PATH = path.join(ROOT, 'config.js');

const DEFAULTS = {
  VENUE: '',
  SEASON: '2026',
  ENTITY_ID: '30895',
  ENTITY_TYPE: 'association',
  GRAPHQL_ENDPOINT: 'https://rugby-au-cms.graphcdn.app/',
  REFRESH_INTERVAL_SECONDS: '60',
  PRE_MATCH_WINDOW_MINUTES: '30',
  POST_MATCH_WINDOW_MINUTES: '90',
  PAGE_RELOAD_HOURS: '6',
  TIMEZONE: 'Australia/Sydney',
};

function parseEnvFile(text) {
  const out = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const fileEnv = fs.existsSync(ENV_PATH)
  ? parseEnvFile(fs.readFileSync(ENV_PATH, 'utf8'))
  : {};

// Treats '' as "not set", not just null/undefined: the GitHub Actions
// workflow always passes every key as an env var, and an unset repo
// variable resolves to an empty string rather than being omitted — plain
// `??` would bake that in as the value instead of falling back to DEFAULTS.
const config = {};
for (const key of Object.keys(DEFAULTS)) {
  config[key] = process.env[key] || fileEnv[key] || DEFAULTS[key];
}

if (!config.VENUE) {
  console.warn(
    'Warning: VENUE is not set (in .env or as an environment variable). ' +
      'The kiosk will show its idle state until VENUE is configured or a ' +
      '?venue= query override is used.'
  );
}

for (const numericKey of [
  'ENTITY_ID',
  'REFRESH_INTERVAL_SECONDS',
  'PRE_MATCH_WINDOW_MINUTES',
  'POST_MATCH_WINDOW_MINUTES',
  'PAGE_RELOAD_HOURS',
]) {
  const n = Number(config[numericKey]);
  if (Number.isNaN(n)) {
    throw new Error(`${numericKey} must be numeric, got: ${config[numericKey]}`);
  }
  config[numericKey] = n;
}

const banner =
  '// GENERATED by scripts/generate-config.js from .env — do not edit by hand.\n';
fs.writeFileSync(
  OUT_PATH,
  `${banner}window.__CONFIG__ = ${JSON.stringify(config, null, 2)};\n`
);

console.log(`Wrote ${path.relative(ROOT, OUT_PATH)}`);
